[package]
name = "motor-fisicas"
authors = ["Arturo García Richardson", "Arturo García Richardson <agrg11@alu.ua.es>"]
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
bevy-inspector-egui = "0.31.0"
bevy_egui = "0.34.1"
rand = "0.9.0"
