[package]
name = "motor-fisicas"
authors = ["Arturo García Richardson", "Arturo García Richardson <agrg11@alu.ua.es>"]
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.2" }
bevy_mod_imgui = "0.6.0"
imgui = "0.12.0"
rand = "0.9.0"
